### ISSUE TITLE
First stable test checklist

### ISSUE THREAD

**Issue by kiro7shiro** [kiro7shiro/k7sSourceCodeManager#8]
## Checklist for things todo before test is achieved.

- [ ] insert some basic error handling. 
  - [ ] write a basic logging function
 - keep in mind a central handler function for all projects.
- [ ] test im/ export function
  - [ ] create folder while export if not exists
  - [ ] test import function
    - [ ] check version number
    - [ ] don't overwrite files if unnecessary
- [ ] test project configuration
  - [ ] create a init function for deafult settings
    - [ ] author
    - [ ] date created
    - [ ] version
    - [ ] description
  - [ ] recheck add, edit and del functions
  - [ ] make shure all errors are handled
    - create a list of all errors
  - [ ] redesign dialog
- [ ] test delete function
  - [ ] don't remove the files that are needed for SCM to function
- [ ] add icons to the ribbon menu
 - try to find a design
